export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const ADD_TOPIC_BEGIN = "ADD_TOPIC_BEGIN"
export const ADD_TOPIC_SUCCESS = "ADD_TOPIC_SUCCESS"
export const ADD_TOPIC_ERROR = "ADD_TOPIC_ERROR"

export const GET_TOPICS_BEGIN = "GET_TOPICS_BEGIN"
export const GET_TOPICS_SUCCESS = "GET_TOPICS_SUCCESS"
export const GET_TOPICS_ERROR = "GET_TOPICS_ERROR"
